#So Young Lee
#Dictionary


# Promonotion Analysis
ha_ua_id_prom = {'name': 'datHA',
                'analysis': 'prom',
                'gaps': [8-2,
                         12-5,
                         14-6,
                         20-15,
                         32-18,
                         25-20,
                         29-22],
                'memory':
                {'T1': {'start': 5,
                        'end': 10,
                        'type': 'L'},
                 'vbar1': {'start': 8,
                           'end': 11,
                           'type': 'I'},
                 'v1': {'start': 11,
                        'end': 37,
                        'type': 'L'},
                 'V1': {'start': 14,
                        'end': 38,
                        'type': 'P'},
                 'Rel': {'start': 18,
                         'end': 34,
                         'type': 'P'},
                 'C2': {'start': 20,
                        'end': 36,
                        'type': 'L'},
                 'T2': {'start': 22,
                        'end': 27,
                        'type': 'L'},
                 'vbar2': {'start': 25,
                           'end': 28,
                           'type': 'I'},
                 'v2': {'start': 28,
                        'end': 31,
                        'type': 'L'},
                 'Vbar2': {'start': 29,
                           'end': 32,
                           'type': 'I'},
                 'N': {'start': 32,
                        'end': 35,
                        'type': 'P'}}}

ha_ua_di_prom = {'name': 'datHA',
                'analysis': 'prom',
                'gaps': [9-2,
                         13-6,
                         14-5,
                         21-16,
                         30-19,
                         26-21,
                         31-24],
                'memory':
                {'T1': {'start': 5,
                        'end': 11,
                        'type': 'L'},
                 'vbar1': {'start': 9,
                           'end': 12,
                           'type': 'I'},
                 'v1': {'start': 12,
                        'end': 38,
                        'type': 'L'},
                 'V1': {'start': 14,
                        'end': 39,
                        'type': 'P'},
                 'DP': {'start': 13,
                        'end': 16,
                        'type': 'I'},
                 'Rel': {'start': 19,
                         'end': 35,
                         'type': 'P'},
                 'C2': {'start': 21,
                        'end': 37,
                        'type': 'L'},
                 'T2': {'start': 23,
                        'end': 28,
                        'type': 'L'},
                 'vbar2': {'start': 26,
                           'end': 29,
                           'type': 'I'},
                 'v2': {'start': 29,
                        'end': 33,
                        'type': 'L'},
                 'V2': {'start': 31,
                        'end': 34,
                        'type': 'P'},
                 'N': {'start': 30,
                        'end': 36,
                        'type': 'P'}}}

ha_a_id_prom = {'name': 'datHA',
                'analysis': 'prom',
                'gaps': [8-2,
                         12-5,
                         14-6,
                         20-15,
                         32-18,
                         25-20,
                         29-22],
                'memory':
                {'T1': {'start': 5,
                        'end': 10,
                        'type': 'L'},
                 'vbar1': {'start': 8,
                           'end': 11,
                           'type': 'I'},
                 'v1': {'start': 11,
                        'end': 37,
                        'type': 'L'},
                 'V1': {'start': 14,
                        'end': 38,
                        'type': 'P'},
                 'Rel': {'start': 18,
                         'end': 34,
                         'type': 'P'},
                 'C2': {'start': 20,
                        'end': 36,
                        'type': 'L'},
                 'T2': {'start': 22,
                        'end': 27,
                        'type': 'L'},
                 'vbar2': {'start': 25,
                           'end': 28,
                           'type': 'I'},
                 'v2': {'start': 28,
                        'end': 31,
                        'type': 'L'},
                 'Vbar2': {'start': 29,
                           'end': 32,
                           'type': 'I'},
                 'N': {'start': 32,
                        'end': 35,
                        'type': 'P'}}}

ha_a_di_prom = {'name': 'datHA',
                'analysis': 'prom',
                'gaps': [9-2,
                         13-6,
                         14-5,
                         21-16,
                         30-19,
                         26-21,
                         31-24],
                'memory':
                {'T1': {'start': 5,
                        'end': 11,
                        'type': 'L'},
                 'vbar1': {'start': 9,
                           'end': 12,
                           'type': 'I'},
                 'v1': {'start': 12,
                        'end': 38,
                        'type': 'L'},
                 'V1': {'start': 14,
                        'end': 39,
                        'type': 'P'},
                 'DP': {'start': 13,
                        'end': 16,
                        'type': 'I'},
                 'Rel': {'start': 19,
                         'end': 35,
                         'type': 'P'},
                 'C2': {'start': 21,
                        'end': 37,
                        'type': 'L'},
                 'T2': {'start': 23,
                        'end': 28,
                        'type': 'L'},
                 'vbar2': {'start': 26,
                           'end': 29,
                           'type': 'I'},
                 'v2': {'start': 29,
                        'end': 33,
                        'type': 'L'},
                 'V2': {'start': 31,
                        'end': 34,
                        'type': 'L'},
                 'N': {'start': 30,
                        'end': 36,
                        'type': 'P'}}}
la_ua_id_prom = {'name': 'datLA',
                'analysis': 'prom',
                'gaps': [7-2,
                         11-5,
                         17-12,
                         30-15,
                         25-17,
                         23-18],
                'memory':
                {'T1': {'start': 5,
                        'end': 9,
                        'type': 'L'},
                 'vbar1': {'start': 7,
                           'end': 10,
                           'type': 'I'},
                 'v1': {'start': 10,
                        'end': 35,
                        'type': 'L'},
                 'V1': {'start': 11,
                        'end': 36,
                        'type': 'P'},
                 'Rel': {'start': 15,
                         'end': 32,
                         'type': 'P'},
                 'C2': {'start': 17,
                        'end': 34,
                        'type': 'L'},
                 'T2': {'start': 20,
                        'end': 28,
                        'type': 'L'},
                 'N1': {'start': 23,
                        'end': 27,
                        'type': 'P'},
                 'v2': {'start': 24,
                        'end': 29,
                        'type': 'L'},
                 'Vbar2': {'start': 25,
                           'end': 30,
                           'type': 'I'},
                 'N': {'start': 30,
                        'end': 33,
                        'type': 'P'}}}

la_ua_di_prom = {'name': 'datLA',
                'analysis': 'prom',
                'gaps': [7-2,
                         11-5,
                         17-12,
                         25-15,
                         26-17,
                         23-18],
                'memory':
                {'T1': {'start': 5,
                        'end': 10,
                        'type': 'L'},
                 'vbar1': {'start': 7,
                           'end': 10,
                           'type': 'I'},
                 'v1': {'start': 10,
                        'end': 35,
                        'type': 'L'},
                 'V1': {'start': 11,
                        'end': 36,
                        'type': 'P'},
                 'Rel': {'start': 15,
                         'end': 32,
                         'type': 'P'},
                 'C2': {'start': 17,
                        'end': 34,
                        'type': 'L'},
                 'T2': {'start': 20,
                        'end': 29,
                        'type': 'L'},
                 'N1': {'start': 23,
                        'end': 28,
                        'type': 'P'},
                 'v2': {'start': 24,
                        'end': 30,
                        'type': 'L'},
                 'Vbar2': {'start': 25,
                           'end': 36,
                           'type': 'I'},
                 'N': {'start': 25,
                        'end': 33,
                        'type': 'P'}}}

la_a_id_prom = {'name': 'datLA',
                'analysis': 'prom',
                'gaps': [8-2,
                         12-5,
                         14-6,
                         20-15,
                         33-18,
                         28-20,
                         26-21],
                'memory':
                {'T1': {'start': 5,
                        'end': 10,
                        'type': 'L'},
                 'vbar1': {'start': 8,
                           'end': 11,
                           'type': 'I'},
                 'v1': {'start': 11,
                        'end': 38,
                        'type': 'L'},
                 'V1': {'start': 14,
                        'end': 39,
                        'type': 'P'},
                 'Rel': {'start': 18,
                         'end': 35,
                         'type': 'P'},
                 'C2': {'start': 20,
                        'end': 37,
                        'type': 'L'},
                 'T2': {'start': 23,
                        'end': 31,
                        'type': 'L'},
                 'N1': {'start': 26,
                        'end': 30,
                        'type': 'P'},
                 'v2': {'start': 27,
                        'end': 32,
                        'type': 'L'},
                 'Vbar2': {'start': 28,
                           'end': 33,
                           'type': 'I'},
                 'N': {'start': 33,
                        'end': 36,
                        'type': 'P'}}}

la_a_di_prom = {'name': 'datLA',
                'analysis': 'prom',
                'gaps': [9-2,
                         13-5,
                         14-6,
                         18-13,
                         26-16,
                         27-18,
                         24-19],
                'memory':
                {'T1': {'start': 5,
                        'end': 10,
                        'type': 'L'},
                 'vbar1': {'start': 8,
                           'end': 11,
                           'type': 'I'},
                 'v1': {'start': 11,
                        'end': 38,
                        'type': 'L'},
                 'V1': {'start': 14,
                        'end': 39,
                        'type': 'P'},
                 'Rel': {'start': 16,
                         'end': 33,
                         'type': 'P'},
                 'C2': {'start': 18,
                        'end': 35,
                        'type': 'L'},
                 'T2': {'start': 21,
                        'end': 30,
                        'type': 'L'},
                 'N1': {'start': 24,
                        'end': 29,
                        'type': 'L'},
                 'vbar2': {'start': 25,
                           'end': 31,
                           'type': 'I'},
                 'v2': {'start': 29,
                        'end': 33,
                        'type': 'L'},
                 'V2': {'start': 27,
                        'end': 32,
                        'type': 'L'},
                 'N': {'start': 26,
                        'end': 34,
                        'type': 'P'}}}

# Wh movement analysis
ha_ua_id_whm = {'name': 'datHA',
                'analysis': 'whm',
                'gaps': [8-2,
                         12-5,
                         14-6,
                         17-14,
                         27-17,
                         24-19,
                         26-21],
                'memory':
                {'T1': {'start': 5,
                        'end': 10,
                        'type': 'L'},
                 'vbar1': {'start': 8,
                           'end': 11,
                           'type': 'I'},
                 'v1': {'start': 11,
                        'end': 37,
                        'type': 'L'},
                 'V1': {'start': 14,
                        'end': 38,
                        'type': 'P'},
                 'D': {'start': 16,
                        'end': 35,
                        'type': 'L'},
                 'C2': {'start': 19,
                        'end': 29,
                        'type': 'L'},
                 'T2': {'start': 21,
                        'end': 31,
                        'type': 'L'},
                 'N1': {'start': 24,
                        'end': 30,
                        'type': 'L'},
                 'v2': {'start': 25,
                        'end': 33,
                        'type': 'L'},
                 'N2': {'start': 26,
                        'end': 32,
                        'type': 'L'},
                 'V2': {'start': 27,
                        'end': 34,
                        'type': 'I'},
                 'N': {'start': 17,
                        'end': 36,
                        'type': 'P'}}}

ha_ua_di_whm = {'name': 'datHA',
                'analysis': 'whm',
                'gaps': [9-2,
                         13-6,
                         14-5,
                         18-13,
                         27-18,
                         25-20,
                         32-23],
                'memory':
                {'T1': {'start': 5,
                        'end': 11,
                        'type': 'L'},
                 'vbar1': {'start': 9,
                           'end': 12,
                           'type': 'I'},
                 'v1': {'start': 12,
                        'end': 38,
                        'type': 'L'},
                 'V1': {'start': 14,
                        'end': 39,
                        'type': 'P'},
                 'DP': {'start': 13,
                        'end': 16,
                        'type': 'L'},
                 'D': {'start': 17,
                        'end': 36,
                        'type': 'L'},
                 'C2': {'start': 20,
                        'end': 29,
                        'type': 'L'},
                 'T2': {'start': 22,
                        'end': 31,
                        'type': 'L'},
                 'N1': {'start': 25,
                        'end': 30,
                        'type': 'L'},
                 'v2': {'start': 26,
                        'end': 34,
                        'type': 'L'},
                 'Vbar2': {'start': 27,
                        'end': 32,
                        'type': 'I'},
                 'V2': {'start': 32,
                        'end': 35,
                        'type': 'I'},
                 'N': {'start': 18,
                        'end': 37,
                        'type': 'P'}}}

ha_a_id_whm = {'name': 'datHA',
                'analysis': 'whm',
                'gaps': [8-2,
                         12-5,
                         14-6,
                         17-14,
                         27-17,
                         24-19,
                         26-21],
                'memory':
                {'T1': {'start': 5,
                        'end': 10,
                        'type': 'L'},
                 'vbar1': {'start': 8,
                           'end': 11,
                           'type': 'I'},
                 'v1': {'start': 11,
                        'end': 37,
                        'type': 'L'},
                 'V1': {'start': 14,
                        'end': 38,
                        'type': 'P'},
                 'D': {'start': 16,
                        'end': 35,
                        'type': 'L'},
                 'C2': {'start': 19,
                        'end': 29,
                        'type': 'L'},
                 'T2': {'start': 21,
                        'end': 31,
                        'type': 'L'},
                 'N1': {'start': 24,
                        'end': 30,
                        'type': 'L'},
                 'v2': {'start': 25,
                        'end': 33,
                        'type': 'L'},
                 'N2': {'start': 26,
                        'end': 32,
                        'type': 'L'},
                 'V2': {'start': 27,
                        'end': 34,
                        'type': 'I'},
                 'N': {'start': 17,
                        'end': 36,
                        'type': 'P'}}}

ha_a_di_whm = {'name': 'datHA',
                'analysis': 'whm',
                'gaps': [9-2,
                         13-6,
                         14-5,
                         18-13,
                         27-18,
                         25-20,
                         32-23],
                'memory':
                {'T1': {'start': 5,
                        'end': 11,
                        'type': 'L'},
                 'vbar1': {'start': 9,
                           'end': 12,
                           'type': 'I'},
                 'v1': {'start': 12,
                        'end': 38,
                        'type': 'L'},
                 'V1': {'start': 14,
                        'end': 39,
                        'type': 'P'},
                 'DP': {'start': 13,
                        'end': 16,
                        'type': 'L'},
                 'D': {'start': 17,
                        'end': 36,
                        'type': 'L'},
                 'C2': {'start': 20,
                        'end': 29,
                        'type': 'L'},
                 'T2': {'start': 22,
                        'end': 31,
                        'type': 'L'},
                 'N1': {'start': 25,
                        'end': 30,
                        'type': 'L'},
                 'v2': {'start': 26,
                        'end': 34,
                        'type': 'L'},
                 'Vbar2': {'start': 27,
                        'end': 32,
                        'type': 'I'},
                 'V2': {'start': 32,
                        'end': 35,
                        'type': 'I'},
                 'N': {'start': 18,
                        'end': 37,
                        'type': 'P'}}}

la_ua_id_whm = {'name': 'datLA',
                'analysis': 'whm',
                'gaps': [7-2,
                         11-5,
                         14-11,
                         24-14,
                         21-16,
                         23-18],
                'memory':
                {'T1': {'start': 5,
                        'end': 9,
                        'type': 'L'},
                 'vbar1': {'start': 7,
                           'end': 10,
                           'type': 'I'},
                 'v1': {'start': 10,
                        'end': 34,
                        'type': 'L'},
                 'V1': {'start': 11,
                        'end': 35,
                        'type': 'P'},
                 'D': {'start': 13,
                        'end': 32,
                        'type': 'L'},
                 'C2': {'start': 16,
                        'end': 26,
                        'type': 'L'},
                 'T2': {'start': 18,
                        'end': 28,
                        'type': 'L'},
                 'N1': {'start': 21,
                        'end': 27,
                        'type': 'P'},
                 'v2': {'start': 22,
                        'end': 30,
                        'type': 'L'},
                 'N2': {'start': 23,
                        'end': 29,
                        'type': 'P'},
                 'V2': {'start': 24,
                        'end': 31,
                        'type': 'P'},
                 'N': {'start': 14,
                        'end': 33,
                        'type': 'P'}}}

la_ua_di_whm = {'name': 'datLA',
                'analysis': 'whm',
                'gaps': [7-2,
                         11-5,
                         14-11,
                         24-14,
                         27-16,
                         22-17],
                'memory':
                {'T1': {'start': 5,
                        'end': 9,
                        'type': 'L'},
                 'vbar1': {'start': 7,
                           'end': 10,
                           'type': 'I'},
                 'v1': {'start': 10,
                        'end': 35,
                        'type': 'L'},
                 'V1': {'start': 11,
                        'end': 36,
                        'type': 'P'},
                 'D': {'start': 13,
                        'end': 33,
                        'type': 'L'},
                 'C2': {'start': 16,
                        'end': 26,
                        'type': 'L'},
                 'T2': {'start': 19,
                        'end': 30,
                        'type': 'L'},
                 'N1': {'start': 22,
                        'end': 29,
                        'type': 'P'},
                 'v2': {'start': 23,
                        'end': 31,
                        'type': 'L'},
                 'Vbar2': {'start': 24,
                           'end': 27,
                           'type': 'I'},
                 'V2': {'start': 27,
                        'end': 32,
                        'type': 'P'},
                 'N': {'start': 14,
                        'end': 34,
                        'type': 'P'}}}

la_a_id_whm = {'name': 'datLA',
               'analysis': 'whm',
               'gaps': [8-2,
                         12-5,
                         14-6,
                         17-14,
                         28-17,
                         27-19,
                         25-20],
                'memory':
                {'T1': {'start': 5,
                        'end': 10,
                        'type': 'L'},
                 'vbar1': {'start': 8,
                           'end': 11,
                           'type': 'I'},
                 'v1': {'start': 11,
                        'end': 38,
                        'type': 'L'},
                 'V1': {'start': 14,
                        'end': 39,
                        'type': 'P'},
                 'D': {'start': 16,
                         'end': 36,
                         'type': 'L'},
                 'C2': {'start': 19,
                        'end': 30,
                        'type': 'L'},
                 'T2': {'start': 22,
                        'end': 33,
                        'type': 'L'},
                 'N1': {'start': 25,
                        'end': 32,
                        'type': 'P'},
                 'v2': {'start': 26,
                        'end': 34,
                        'type': 'L'},
                 'N2': {'start': 27,
                        'end': 31,
                        'type': 'P'},
                 'V2': {'start': 28,
                        'end': 35,
                        'type': 'P'},
                 'N': {'start': 17,
                        'end': 37,
                        'type': 'P'}}}

la_a_di_whm = {'name': 'datLA',
                'analysis': 'whm',
                'gaps': [8-2,
                         12-5,
                         36-6,
                         15-12,
                         25-15,
                         28-17,
                         23-18],
                'memory':
                {'T1': {'start': 5,
                        'end': 10,
                        'type': 'L'},
                 'vbar1': {'start': 8,
                           'end': 11,
                           'type': 'I'},
                 'v1': {'start': 11,
                        'end': 38,
                        'type': 'L'},
                 'Vbar1': {'start': 12,
                        'end': 36,
                        'type': 'I'},
                 'V1': {'start': 36,
                        'end': 39,
                        'type': 'P'},
                 'D': {'start': 14,
                        'end': 34,
                        'type': 'L'},
                 'C2': {'start': 17,
                        'end': 27,
                        'type': 'L'},
                 'T2': {'start': 20,
                        'end': 31,
                        'type': 'L'},
                 'N1': {'start': 23,
                        'end': 30,
                        'type': 'P'},
                 'v2': {'start': 24,
                        'end': 32,
                        'type': 'L'},
                 'Vbar2': {'start': 25,
                           'end': 28,
                           'type': 'I'},
                 'V2': {'start': 28,
                        'end': 33,
                        'type': 'P'},
                 'N': {'start': 15,
                        'end': 35,
                        'type': 'P'}}}
